/**
 * MPP attribution memo encoding for Hedera native transactions.
 *
 * Identical byte layout to Tempo's Attribution.ts — ensures compatibility
 * with the mppx ecosystem's challenge-binding verification.
 *
 * ## Byte Layout (32 bytes)
 *
 * | Offset | Size | Field                                     |
 * |--------|------|-------------------------------------------|
 * | 0..3   | 4    | TAG = keccak256("mpp")[0..3]               |
 * | 4      | 1    | version (0x01)                            |
 * | 5..14  | 10   | serverId = keccak256(serverId)[0..9]       |
 * | 15..24 | 10   | clientId = keccak256(clientId)[0..9] or 0s |
 * | 25..31 | 7    | nonce = keccak256(challengeId)[0..6]       |
 *
 * On Tempo, this memo is embedded in `transferWithMemo(address,uint256,bytes32)`.
 * On Hedera, it is embedded in the native transaction memo via `setTransactionMemo()`.
 *
 * @module
 */

import { keccak256, toBytes, toHex, hexToBytes } from 'viem';

/** First 4 bytes of keccak256("mpp") — the on-chain MPP tag. */
export const tag = keccak256(toBytes('mpp')).slice(0, 10) as `0x${string}`; // "0x" + 8 hex chars = 4 bytes

/** Current memo version. */
const version = 0x01;

/** 10 zero bytes representing an anonymous (no clientId) client. */
export const anonymous = '0x00000000000000000000' as const;

/**
 * Computes a 10-byte fingerprint from a string via keccak256.
 * @internal
 */
function fingerprint(value: string): Uint8Array {
  const hash = keccak256(toBytes(value));
  return hexToBytes(hash.slice(0, 22) as `0x${string}`); // "0x" + 20 hex chars = 10 bytes
}

/**
 * Computes the 7-byte challenge-bound nonce: keccak256(challengeId)[0..6].
 * @internal
 */
export function challengeNonce(challengeId: string): Uint8Array {
  const hash = keccak256(toBytes(challengeId));
  return hexToBytes(hash.slice(0, 16) as `0x${string}`); // "0x" + 14 hex chars = 7 bytes
}

/**
 * Encodes an MPP attribution memo as a `0x`-prefixed hex string (32 bytes).
 *
 * @example
 * ```ts
 * import * as Attribution from './attribution.js'
 * const memo = Attribution.encode({ challengeId: 'ch_123', serverId: 'api.example.com' })
 * ```
 */
export function encode(params: {
  challengeId: string;
  clientId?: string;
  serverId: string;
}): `0x${string}` {
  const { serverId, clientId, challengeId } = params;
  const buf = new Uint8Array(32);

  buf.set(hexToBytes(tag), 0);
  buf[4] = version;
  buf.set(fingerprint(serverId), 5);
  if (clientId) buf.set(fingerprint(clientId), 15);
  buf.set(challengeNonce(challengeId), 25);

  return toHex(buf);
}

/**
 * Checks whether a memo was generated by the MPP attribution system.
 */
export function isMppMemo(memo: `0x${string}`): boolean {
  if (memo.length !== 66) return false;
  const memoTag = memo.slice(0, 10) as `0x${string}`;
  const memoVersion = Number.parseInt(memo.slice(10, 12), 16);
  return memoTag.toLowerCase() === tag.toLowerCase() && memoVersion === version;
}

/**
 * Verifies that a memo's server fingerprint matches the given serverId.
 */
export function verifyServer(memo: `0x${string}`, serverId: string): boolean {
  if (!isMppMemo(memo)) return false;
  const memoServerHex = `0x${memo.slice(12, 32)}` as `0x${string}`;
  const expectedHex = toHex(fingerprint(serverId)) as `0x${string}`;
  return memoServerHex.toLowerCase() === expectedHex.toLowerCase();
}

/**
 * Decodes an MPP attribution memo into its constituent parts.
 */
export function decode(memo: `0x${string}`): {
  version: number;
  serverFingerprint: `0x${string}`;
  clientFingerprint: `0x${string}` | null;
  nonce: `0x${string}`;
} | null {
  if (!isMppMemo(memo)) return null;

  const memoVersion = Number.parseInt(memo.slice(10, 12), 16);
  const serverFingerprint = `0x${memo.slice(12, 32)}` as `0x${string}`;
  const clientHex = `0x${memo.slice(32, 52)}` as `0x${string}`;
  const nonce = `0x${memo.slice(52)}` as `0x${string}`;
  const clientFingerprint =
    clientHex.toLowerCase() === anonymous.toLowerCase() ? null : clientHex;

  return { version: memoVersion, serverFingerprint, clientFingerprint, nonce };
}

/**
 * Verifies that a memo's nonce is bound to the given challengeId.
 */
export function verifyChallengeBinding(
  memo: `0x${string}`,
  challengeId: string,
): boolean {
  const decoded = decode(memo);
  if (!decoded) return false;
  const expectedNonce = toHex(challengeNonce(challengeId));
  return decoded.nonce.toLowerCase() === expectedNonce.toLowerCase();
}
